name = "WIP Smarter Possesed Chassis"
description = "Make the lunar affinity of wx more reliable and less of a dummy, now they try to evade enemies and dangers, eat and repair even in combat, their aggro is reduced to bosses and more to come! Now make them usefull in more complex bosses fights like Celestial Champion and Shadow Pieces."
author = "Ruperstiltskin"
version = "1.0"
forumthread = ""
api_version = 10
dst_compatible = true
all_clients_require_mod = true
client_only_mod = false
icon_atlas = "modicon.xml"
icon = "modicon.tex"